mysql: &mysql
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /tmp/mysql.sock

defaults: &defaults
  encoding: utf8
  reconnect: false
  pool: 5
  <<: *<%= ENV['DB'] || "mysql" %>

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults

cucumber:
  <<: *test